name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag tests-playwright-image:$(date +%s)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Activează Buildx pentru Docker

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run Playwright tests in Docker
      run: docker run --rm playwright-tests
      
